package me.liuweiqiang.locking.dao;

import java.util.List;
import me.liuweiqiang.locking.dao.model.Token;
import me.liuweiqiang.locking.dao.model.TokenExample;
import org.apache.ibatis.annotations.Param;

public interface TokenDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    long countByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int deleteByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int insertSelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    List<Token> selectByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    Token selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int updateByExampleSelective(@Param("record") Token record, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int updateByExample(@Param("record") Token record, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int updateByPrimaryKeySelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locking..token
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    int updateByPrimaryKey(Token record);
}