package me.liuweiqiang.locking.dao.model;

import java.util.Date;

public class Lock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..lock.id
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..lock.space
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    private String space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..lock.create_time
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..lock.id
     *
     * @return the value of locking..lock.id
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..lock.id
     *
     * @param id the value for locking..lock.id
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..lock.space
     *
     * @return the value of locking..lock.space
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public String getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..lock.space
     *
     * @param space the value for locking..lock.space
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public void setSpace(String space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..lock.create_time
     *
     * @return the value of locking..lock.create_time
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..lock.create_time
     *
     * @param createTime the value for locking..lock.create_time
     *
     * @mbg.generated Sun Feb 20 23:54:15 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}