package me.liuweiqiang.locking.dao.model;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..resource.id
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..resource.resource_key
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    private String resourceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..resource.value
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..resource.id
     *
     * @return the value of locking..resource.id
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..resource.id
     *
     * @param id the value for locking..resource.id
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..resource.resource_key
     *
     * @return the value of locking..resource.resource_key
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..resource.resource_key
     *
     * @param resourceKey the value for locking..resource.resource_key
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..resource.value
     *
     * @return the value of locking..resource.value
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..resource.value
     *
     * @param value the value for locking..resource.value
     *
     * @mbg.generated Mon Feb 21 00:20:13 CST 2022
     */
    public void setValue(String value) {
        this.value = value;
    }
}