package me.liuweiqiang.locking.dao.model;

public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..token.id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..token.resource_key
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    private String resourceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locking..token.token_aka_locking_id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    private Long tokenAkaLockingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..token.id
     *
     * @return the value of locking..token.id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..token.id
     *
     * @param id the value for locking..token.id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..token.resource_key
     *
     * @return the value of locking..token.resource_key
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..token.resource_key
     *
     * @param resourceKey the value for locking..token.resource_key
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locking..token.token_aka_locking_id
     *
     * @return the value of locking..token.token_aka_locking_id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public Long getTokenAkaLockingId() {
        return tokenAkaLockingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locking..token.token_aka_locking_id
     *
     * @param tokenAkaLockingId the value for locking..token.token_aka_locking_id
     *
     * @mbg.generated Sun Feb 20 23:54:28 CST 2022
     */
    public void setTokenAkaLockingId(Long tokenAkaLockingId) {
        this.tokenAkaLockingId = tokenAkaLockingId;
    }
}